### ISSUE TITLE
Updated texts

### ISSUE THREAD

**Issue by MarcusJoh** [rugsmunny/HearingBuds_HearingTest#10]
Some text changes for the result pages, check the comments in figma

And there are some minor corrections from Sarah as well. 

Figma link to the design 

https://www.figma.com/design/ggstBRlNWIhSIuPuZvk1zV/Hearingtest?node-id=1228-2109&t=tMCPeXCCA1Iljrs8-1

please check them and update this issue when you have corrected them

**Comment by Carl-B-Doro** [comment]
This does not seem to be implemented. Text at the moment:

"Based on your online hearing test results, we recommend our HearingBuds for its excellent sound performance during calls and listening to music."

**Comment by rugsmunny** [comment]
I have reviewed and updated all texts to ensure they match the design specifications provided in Figma.

**Comment by MarcusJoh** [comment]
@rugsmunny the repo have not been punched to for 2 months, are you testing it on an other repo?

**Comment by rugsmunny** [comment]
all texts are up to date with figma design; minor css changes and .js refactoring done.
