### ISSUE TITLE
Dropdown menu does not work on Safari

### ISSUE THREAD

**Issue by Carl-B-Doro** [rugsmunny/HearingBuds_HearingTest#12]
Dropdown menu does not work on safari. Check support of dropdown element with different browsers. 
On Safari they are not clickable at all.

**Comment by Carl-B-Doro** [comment]
Only possible to "Pick you gender" once iOS in Chrome. Need to pick year of birth again before being able to pick Gender.

**Comment by rugsmunny** [comment]
issue solved; tested on browser, touch, android and ios
