### ISSUE TITLE
Next button greyed out when coosing different combination 

### ISSUE THREAD

**Issue by doroOma** [rugsmunny/HearingBuds_HearingTest#14]
![Screenshot 2024-07-11 094913](https://github.com/rugsmunny/HearingBuds_HearingTest/assets/157350079/da3a4d3a-5173-4407-9671-904d6bfb5853)

When choosing 2 → 3 → 1 / 3 → 2 → 1  the “Next” button still greyed out in which you have to choose again in either of the (1-2-3)  to be activated. Same issue found when tested on android phone. 

![e49ee23d-12b4-407b-8573-f9b37dacdf23](https://github.com/rugsmunny/HearingBuds_HearingTest/assets/157350079/c14b6fad-b05a-45b0-8e76-adcfd1b8757b)

**Comment by rugsmunny** [comment]
Issue solved and pushed.
