### ISSUE TITLE
The site does not scale to different monitor size

### ISSUE THREAD

**Issue by jensbenthin** [rugsmunny/HearingBuds_HearingTest#2]
When using the site on my laptop, the info in the screen gets all mixed up due to less space. The progress bar is scaling and shown on the middle of the screen, the rest of the info is not scaling.

**Comment by rugsmunny** [comment]
These issues have been taken care of and I am currently working on the phone/tablet part of this module. Please get back to me if this is not the case or if you find any other issues. I will gladly take care of it.

**Comment by jensbenthin** [comment]
Tested OK
