### ISSUE TITLE
Birth year dropdown looks strange

### ISSUE THREAD

**Issue by jensbenthin** [rugsmunny/HearingBuds_HearingTest#4]
![Screenshot 2024-05-06 151601](https://github.com/rugsmunny/HearingBuds_HearingTest/assets/66470679/8ab005ff-32a9-4ac5-a88e-fcaa6b687a52)

Please see the attached image. The dropdown does look strange with the big box and small years adjusted to the right.

**Comment by rugsmunny** [comment]
Although I agree, it is in its closed state following measures set by UX.
My initial dropdown had the same width plus some padding as the digits. If
you can get that cleared then I can make that change. If you perhaps have
another suggestion/solution, please feel free to share it.

/Karim

Den mån 6 maj 2024 15:17jensbenthin ***@***.***> skrev:

**Comment by rugsmunny** [comment]
Should we close this one or are we awaiting further instructions?

**Comment by MarcusJoh** [comment]
Approved
