### ISSUE TITLE
Tones should start to play automatically

### ISSUE THREAD

**Issue by jensbenthin** [rugsmunny/HearingBuds_HearingTest#6]
The tone should automatically start playing when you enter the page. Right now you have to adjust the volume up or down before you hear any sound. The tone should start automatically.

As of right now, all tones but the first is starting automatically.

**Comment by rugsmunny** [comment]
Solved. Tune is playing as soon as the test slide is loaded and as well while changing frequency.

**Comment by jensbenthin** [comment]
This is Tested OK.
